version: "3.8"

services:
  dev_app:
    container_name: dev_app
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 1111 --reload"
    volumes:
      - ../../../:/home/app
    env_file:
      - .env
    ports:
      - "2222:1111"

    depends_on:
      - dev_db

  dev_db:
    container_name: dev_db
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=education_platform
    ports:
      - "5440:5432"
    restart: always


volumes:
  postgres_data:
